Add TakeLastStreamTransformer and takeLast extension
ReactiveX/rxdart pull request #546
Opened 2021-01-27 10:57 UTC by ThomasKliszowski

Fix #497

2021-01-27 13:49 UTC, ThomasKliszowski commented
Codecov does not update, the coverage is 100%, and the global coverage diff is +0.06%.

https://codecov.io/gh/ReactiveX/rxdart/commit/a210c26a65ae4d09bc4a4373fb2db63a8bcf2b68/

2021-01-27 18:12 UTC, hoc081098 requested changes

2021-01-27 18:12 UTC, hoc081098 commented on lib/src/transformers/take_last.dart
> +  FutureOr onCancel(EventSink<T> sink) {}
Should clear list/queue on cancel.

2021-01-27 18:12 UTC, hoc081098 commented on lib/src/transformers/take_last.dart
> +  ///       .transform(TakeLastStreamTransformer(3))
Should be `Stream.fromIterable([1, 2, 3, 4, 5]).takeLast(3)`. Because it is example for `takeLast` extension method :))

2021-01-27 18:12 UTC, hoc081098 commented on test/transformers/take_last_test.dart
> +  test('Rx.takeLast.accidentalBroadcast', () async {
IMO, `Rx.takeLast.singleSubscription` or `Rx.takeLast.single.subscription` is better name.

2021-01-28 08:37 UTC, ThomasKliszowski commented on lib/src/transformers/take_last.dart
> +  List<T> buffer = [];
Way better indeed.

2021-01-28 08:41 UTC, ThomasKliszowski commented on lib/src/transformers/take_last.dart
> +  FutureOr onCancel(EventSink<T> sink) {}
`onCancel` can be called multiple times, right? Could be a problem if the queue is cleared?

2021-01-28 08:41 UTC, ThomasKliszowski commented on lib/src/transformers/take_last.dart
> +  ///       .transform(TakeLastStreamTransformer(3))
Good catch.

2021-01-28 10:06 UTC, hoc081098 commented on lib/src/transformers/take_last.dart
> +  FutureOr onCancel(EventSink<T> sink) {}
When cancelling subscription or calling sink.close(), onCancel will be called.
For broadcast stream, onCancel can be called multiples times, but we only focus from `onListen` untill `onCancel`.

For example, I copied from `sdk`:
```dart
   * The returned stream is a broadcast stream if this stream is.
   * For a broadcast stream, the events are only counted from the time
   * the returned stream is listened to.
   */
  Stream<T> skip(int count) {
    return new _SkipStream<T>(this, count);
  }
```

```suggestion

  @override
  void close(EventSink<T> sink) {
    queue.forEach(sink.add);
    sink.close(); // <- also call onCancel
  }

  @override
  FutureOr onCancel(EventSink<T> sink) => queue.clear();

```

2021-01-28 19:08 UTC, ThomasKliszowski commented on lib/src/transformers/take_last.dart
> +  FutureOr onCancel(EventSink<T> sink) {}
OK that's perfect, thanks!

2021-01-29 02:11 UTC, hoc081098 approved these changes

2021-01-29 02:13 UTC, merged