add SkipLastStreamTransformer and skipLast extension
ReactiveX/rxdart pull request #553
Opened 2021-03-03 09:44 UTC by HannibalKcc

``` dart
Stream.fromIterable([1, 2, 3, 4, 5])
    .skipLast(3)
    .listen(print); // prints 1, 2
```

2021-03-04 02:02 UTC, hoc081098 requested changes

2021-03-04 02:02 UTC, hoc081098 commented on lib/src/transformers/skip_last.dart
> +    queue.take(queue.length - count).forEach(sink.add);
Missing check if `queue.length - count` is zero or negative?

2021-03-04 02:40 UTC, HannibalKcc commented on lib/src/transformers/skip_last.dart
> +    queue.take(queue.length - count).forEach(sink.add);
Thank you,i added missing parts already.Check it again pls.

2021-03-04 07:01 UTC, hoc081098 commented on lib/src/transformers/skip_last.dart
> +  void addError(EventSink<T> sink, Object e, [StackTrace? st]) =>
I have recently updated on master branch. Please update it

2021-03-04 07:38 UTC, HannibalKcc commented on lib/src/transformers/skip_last.dart
> +  void addError(EventSink<T> sink, Object e, [StackTrace? st]) =>
done~

2021-03-06 08:42 UTC, hoc081098 approved these changes
LGTM

2021-03-06 08:43 UTC, merged